"""empty message

Revision ID: 66e0782ac629
Revises: c04491b9bf28
Create Date: 2025-11-14 15:00:39.742660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e0782ac629'
down_revision = 'c04491b9bf28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seo_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sitemap_lastmod', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('robots_txt_lastmod', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seo_settings', schema=None) as batch_op:
        batch_op.drop_column('robots_txt_lastmod')
        batch_op.drop_column('sitemap_lastmod')

    # ### end Alembic commands ###
