"""empty message

Revision ID: c04491b9bf28
Revises: 
Create Date: 2025-11-14 11:36:32.490922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04491b9bf28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_title', sa.String(length=200), nullable=True),
    sa.Column('site_description', sa.Text(), nullable=True),
    sa.Column('site_keywords', sa.Text(), nullable=True),
    sa.Column('site_author', sa.String(length=100), nullable=True),
    sa.Column('site_logo', sa.String(length=255), nullable=True),
    sa.Column('favicon', sa.String(length=255), nullable=True),
    sa.Column('google_analytics_id', sa.String(length=50), nullable=True),
    sa.Column('baidu_analytics_id', sa.String(length=50), nullable=True),
    sa.Column('social_media_links', sa.Text(), nullable=True),
    sa.Column('custom_head_code', sa.Text(), nullable=True),
    sa.Column('robots_txt', sa.Text(), nullable=True),
    sa.Column('sitemap_url', sa.String(length=255), nullable=True),
    sa.Column('twitter_handle', sa.String(length=50), nullable=True),
    sa.Column('og_image', sa.String(length=255), nullable=True),
    sa.Column('default_canonical_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seo_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('seo_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('seo_keywords', sa.Text(), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seo_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('seo_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('seo_keywords', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('seo_og_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('seo_og_image')
        batch_op.drop_column('seo_keywords')
        batch_op.drop_column('seo_description')
        batch_op.drop_column('seo_title')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('seo_keywords')
        batch_op.drop_column('seo_description')
        batch_op.drop_column('seo_title')

    op.drop_table('seo_settings')
    # ### end Alembic commands ###
